$axure.loadCurrentPage({
  "url":"search_-_name.html",
  "generationDate":new Date(1427775475222.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2adecd156a564e2a80e100a0fef19968",
    "type":"Axure:Page",
    "name":"Search - Name",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f519682e90c41779975b446616a3158",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"094db150b08443a38afa5f9963d6deb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b7f38858308248ae985da0eda7d70cf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":483,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34211ac652164f42bfa2c8744aba4d86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":483,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11d8ea809c9e486f9be67c6ff5f67069",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":13},
            "size":{
              "width":137,
              "height":137},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e11ca2868e415d89c5a0d2cfe44254",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":13},
                "size":{
                  "width":137,
                  "height":137},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"7e3459657ceb4da88aa9f44770b78669",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u8_line.png"}},
{
          "id":"3b21aa350a784be08c05210166e85dc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":573.5,
              "y":16.5},
            "size":{
              "width":130,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c030128bd64147e38d4f1e6ed9b27c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573.5,
                  "y":16.5},
                "size":{
                  "width":130,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_select/u7.png"}},
{
          "id":"3fcd75b9eb4c4c15b59aa5f9fc08de92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":40,
              "y":180},
            "size":{
              "width":660,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3198d2ab81f84ab4b100d8e8246a4dee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":40,
                  "y":180},
                "size":{
                  "width":660,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f36e52c37c44778823d9e6d9637b7ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":40,
              "y":280},
            "size":{
              "width":220,
              "height":70},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f76686127e54e3b8815a901a5b2aa5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":40,
                  "y":280},
                "size":{
                  "width":220,
                  "height":70},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_-_name/u11.png"}},
{
          "id":"2c473b4ff10440008944e3978d28a52d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":40,
              "y":360},
            "size":{
              "width":660,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c620e00dcd143af849937a2b91a224f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":40,
                  "y":360},
                "size":{
                  "width":660,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a32fe6ab6a4cfdb60b5bdb8f886cd0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontSize":"28px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":270,
              "y":280},
            "size":{
              "width":430,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show SearchButton fade 200 ms",
                      "objectsToFades":[{
                          "objectPath":["832c21f338c842898777b0174916284b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":200,
                              "showType":"none"}}}]}]}]}}},
{
          "id":"832c21f338c842898777b0174916284b",
          "label":"SearchButton",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":20,
              "y":1140},
            "size":{
              "width":684,
              "height":110},
            "visible":false,
            "borderWidth":"3",
            "cornerRadiusTopLeft":"20",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43952ecd250475fb4bd0c63bffaacbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":20,
                  "y":1140},
                "size":{
                  "width":684,
                  "height":110},
                "visible":false,
                "borderWidth":"3",
                "cornerRadiusTopLeft":"20",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_-_name/searchbutton_u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f519682e90c41779975b446616a3158":{
      "scriptId":"u0"},
    "094db150b08443a38afa5f9963d6deb1":{
      "scriptId":"u1"},
    "b7f38858308248ae985da0eda7d70cf9":{
      "scriptId":"u2"},
    "34211ac652164f42bfa2c8744aba4d86":{
      "scriptId":"u3"},
    "11d8ea809c9e486f9be67c6ff5f67069":{
      "scriptId":"u4"},
    "d1e11ca2868e415d89c5a0d2cfe44254":{
      "scriptId":"u5"},
    "7e3459657ceb4da88aa9f44770b78669":{
      "scriptId":"u6"},
    "3b21aa350a784be08c05210166e85dc4":{
      "scriptId":"u7"},
    "c030128bd64147e38d4f1e6ed9b27c58":{
      "scriptId":"u8"},
    "3fcd75b9eb4c4c15b59aa5f9fc08de92":{
      "scriptId":"u9"},
    "3198d2ab81f84ab4b100d8e8246a4dee":{
      "scriptId":"u10"},
    "7f36e52c37c44778823d9e6d9637b7ba":{
      "scriptId":"u11"},
    "7f76686127e54e3b8815a901a5b2aa5f":{
      "scriptId":"u12"},
    "2c473b4ff10440008944e3978d28a52d":{
      "scriptId":"u13"},
    "7c620e00dcd143af849937a2b91a224f":{
      "scriptId":"u14"},
    "16a32fe6ab6a4cfdb60b5bdb8f886cd0":{
      "scriptId":"u15"},
    "832c21f338c842898777b0174916284b":{
      "scriptId":"u16"},
    "a43952ecd250475fb4bd0c63bffaacbc":{
      "scriptId":"u17"}}});