$axure.loadCurrentPage({
  "url":"search_-_class_lvl.html",
  "generationDate":new Date(1427775475383.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"49c6b8693b5e4e4fa2ab91332d080001",
    "type":"Axure:Page",
    "name":"Search - Class/Lvl",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5e87f9a26bec4d30b3b2e07959d3f1e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"323ccd424dff45b5981c75a0ede2cfe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"81aad5419d004b979f35d9a20f4144ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":483,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6c2bb31e41f4a629181005056b24d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":483,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8947ec764bc74e6c8eedfa4a14dfaa43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":13},
            "size":{
              "width":137,
              "height":137},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aa0e5c682574954b50b1b7680b87573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":13},
                "size":{
                  "width":137,
                  "height":137},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"1912f13575bc434d8f4ab1660ea4fea5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u8_line.png"}},
{
          "id":"1f86eb5897464f0a880630124096fd57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":573.5,
              "y":16.5},
            "size":{
              "width":130,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49e8000504204e8d9ae1f77561b23045",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573.5,
                  "y":16.5},
                "size":{
                  "width":130,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_select/u7.png"}},
{
          "id":"22502bd6a8f74b59b8c685bb37dd3945",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":40,
              "y":180},
            "size":{
              "width":660,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe1462bb88a3488b8751c6537ac8b500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":40,
                  "y":180},
                "size":{
                  "width":660,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad4b2af52a6f4a858822e0238d58f853",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":40,
              "y":280},
            "size":{
              "width":220,
              "height":70},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bbc3f96eb3a4c82aae98533755300bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":40,
                  "y":280},
                "size":{
                  "width":220,
                  "height":70},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_-_name/u11.png"}},
{
          "id":"86a16787f8134b49808683a665b463ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":40,
              "y":360},
            "size":{
              "width":660,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a463747863bb43879d3f4a12edb2b85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":40,
                  "y":360},
                "size":{
                  "width":660,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ffc2a8041d742ac836fd271b4173ac9",
          "label":"SearchButton",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":20,
              "y":1140},
            "size":{
              "width":684,
              "height":110},
            "visible":false,
            "borderWidth":"3",
            "cornerRadiusTopLeft":"20",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93255b5b80514a33a386a3c400b2a4d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":20,
                  "y":1140},
                "size":{
                  "width":684,
                  "height":110},
                "visible":false,
                "borderWidth":"3",
                "cornerRadiusTopLeft":"20",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_-_name/searchbutton_u16.png"}},
{
          "id":"0056d7cfc249432697605236bf056f59",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":270,
              "y":280},
            "size":{
              "width":437,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show SearchButton fade 200 ms",
                      "objectsToFades":[{
                          "objectPath":["5ffc2a8041d742ac836fd271b4173ac9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":200,
                              "showType":"none"}}}]}]}]}}},
{
          "id":"d986f78b23134ad1ad994634725a2c9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":40,
              "y":510},
            "size":{
              "width":220,
              "height":70},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"377bae486ebe478fbe66acffd07d30ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":40,
                  "y":510},
                "size":{
                  "width":220,
                  "height":70},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_-_name/u11.png"}},
{
          "id":"0e7499f41b624bb3bc9236179cfaf343",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":270,
              "y":510},
            "size":{
              "width":437,
              "height":70}},
          "adaptiveStyles":{
}},
{
          "id":"45c5be09d88345b29beafb09ee02e898",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":40,
              "y":600},
            "size":{
              "width":660,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d869644ca0c4b9091b9d330ba7dd771",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":40,
                  "y":600},
                "size":{
                  "width":660,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5e87f9a26bec4d30b3b2e07959d3f1e0":{
      "scriptId":"u0"},
    "323ccd424dff45b5981c75a0ede2cfe9":{
      "scriptId":"u1"},
    "81aad5419d004b979f35d9a20f4144ca":{
      "scriptId":"u2"},
    "e6c2bb31e41f4a629181005056b24d3b":{
      "scriptId":"u3"},
    "8947ec764bc74e6c8eedfa4a14dfaa43":{
      "scriptId":"u4"},
    "9aa0e5c682574954b50b1b7680b87573":{
      "scriptId":"u5"},
    "1912f13575bc434d8f4ab1660ea4fea5":{
      "scriptId":"u6"},
    "1f86eb5897464f0a880630124096fd57":{
      "scriptId":"u7"},
    "49e8000504204e8d9ae1f77561b23045":{
      "scriptId":"u8"},
    "22502bd6a8f74b59b8c685bb37dd3945":{
      "scriptId":"u9"},
    "fe1462bb88a3488b8751c6537ac8b500":{
      "scriptId":"u10"},
    "ad4b2af52a6f4a858822e0238d58f853":{
      "scriptId":"u11"},
    "1bbc3f96eb3a4c82aae98533755300bd":{
      "scriptId":"u12"},
    "86a16787f8134b49808683a665b463ff":{
      "scriptId":"u13"},
    "a463747863bb43879d3f4a12edb2b85a":{
      "scriptId":"u14"},
    "5ffc2a8041d742ac836fd271b4173ac9":{
      "scriptId":"u15"},
    "93255b5b80514a33a386a3c400b2a4d9":{
      "scriptId":"u16"},
    "0056d7cfc249432697605236bf056f59":{
      "scriptId":"u17"},
    "d986f78b23134ad1ad994634725a2c9d":{
      "scriptId":"u18"},
    "377bae486ebe478fbe66acffd07d30ec":{
      "scriptId":"u19"},
    "0e7499f41b624bb3bc9236179cfaf343":{
      "scriptId":"u20"},
    "45c5be09d88345b29beafb09ee02e898":{
      "scriptId":"u21"},
    "9d869644ca0c4b9091b9d330ba7dd771":{
      "scriptId":"u22"}}});