$axure.loadCurrentPage({
  "url":"search_select.html",
  "generationDate":new Date(1427775475077.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e9c544e70f9749a299ab1e918ee9d405",
    "type":"Axure:Page",
    "name":"Search Select",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25f290c1bbcb419aa106444ec14b6172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":720,
              "height":1280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eda270b52d04833a65b4dab8d3ecd47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":720,
                  "height":1280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3349fb386de84ad78bb3367afb778e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":483,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0596868276ab41599141a3635e3f4fe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":483,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdc585430f6449ba880f66999e238097",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":13},
            "size":{
              "width":137,
              "height":137},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e6ffac54a274e938a17b5b4f3f7e155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":13},
                "size":{
                  "width":137,
                  "height":137},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"ae8aed06e2574bf598a7645d2c4cdfe6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":720,
              "height":10},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u8_line.png"}},
{
          "id":"fd226240e3d0453490a4d526268d5870",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":573.5,
              "y":16.5},
            "size":{
              "width":130,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7fa0f4323de469b81b63a3c83924f98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573.5,
                  "y":16.5},
                "size":{
                  "width":130,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_select/u7.png"}},
{
          "id":"a0219a6ee209485e953982fc3f534c96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"40px",
            "location":{
              "x":40,
              "y":180},
            "size":{
              "width":660,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b687b02340c545f9a445202eaa7a5958",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"40px",
                "location":{
                  "x":40,
                  "y":180},
                "size":{
                  "width":660,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2d6ed6d047d48e5814e4fe3a890b34b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":40,
              "y":280},
            "size":{
              "width":220,
              "height":70},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"20",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cf0db75a43a46548b6e9c76430f9c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":40,
                  "y":280},
                "size":{
                  "width":220,
                  "height":70},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"20",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Search - Name in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"search_-_name.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search_select/u11.png"}},
{
          "id":"51bfb5182f604e698adc2b8e9964b0a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":40,
              "y":590},
            "size":{
              "width":220,
              "height":70},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"20",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc3fc51fce1946349ae3dc4484feb0fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":40,
                  "y":590},
                "size":{
                  "width":220,
                  "height":70},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"20",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Search - Class/Lvl in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"search_-_class_lvl.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search_select/u11.png"}},
{
          "id":"a34b26bdcd7241e8bcf39ff34026d166",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":310},
            "size":{
              "width":430,
              "height":10},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search_select/u15_line.png"}},
{
          "id":"3136e62a1edf4e749b001059abd8b4f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":620},
            "size":{
              "width":430,
              "height":10},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search_select/u15_line.png"}},
{
          "id":"85dbb37fd1e64ce39a16adb54d13eeb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":40,
              "y":360},
            "size":{
              "width":660,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bace2052300c413dbd368285b78a673e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":40,
                  "y":360},
                "size":{
                  "width":660,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"362c9cfbcdfa49afb61a937a89c1ccdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":40,
              "y":672},
            "size":{
              "width":660,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0efaec3d23c4fdaab7d58c9d6fdf1f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":40,
                  "y":672},
                "size":{
                  "width":660,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "25f290c1bbcb419aa106444ec14b6172":{
      "scriptId":"u0"},
    "1eda270b52d04833a65b4dab8d3ecd47":{
      "scriptId":"u1"},
    "3349fb386de84ad78bb3367afb778e56":{
      "scriptId":"u2"},
    "0596868276ab41599141a3635e3f4fe4":{
      "scriptId":"u3"},
    "bdc585430f6449ba880f66999e238097":{
      "scriptId":"u4"},
    "2e6ffac54a274e938a17b5b4f3f7e155":{
      "scriptId":"u5"},
    "ae8aed06e2574bf598a7645d2c4cdfe6":{
      "scriptId":"u6"},
    "fd226240e3d0453490a4d526268d5870":{
      "scriptId":"u7"},
    "b7fa0f4323de469b81b63a3c83924f98":{
      "scriptId":"u8"},
    "a0219a6ee209485e953982fc3f534c96":{
      "scriptId":"u9"},
    "b687b02340c545f9a445202eaa7a5958":{
      "scriptId":"u10"},
    "d2d6ed6d047d48e5814e4fe3a890b34b":{
      "scriptId":"u11"},
    "0cf0db75a43a46548b6e9c76430f9c44":{
      "scriptId":"u12"},
    "51bfb5182f604e698adc2b8e9964b0a6":{
      "scriptId":"u13"},
    "bc3fc51fce1946349ae3dc4484feb0fb":{
      "scriptId":"u14"},
    "a34b26bdcd7241e8bcf39ff34026d166":{
      "scriptId":"u15"},
    "3136e62a1edf4e749b001059abd8b4f4":{
      "scriptId":"u16"},
    "85dbb37fd1e64ce39a16adb54d13eeb8":{
      "scriptId":"u17"},
    "bace2052300c413dbd368285b78a673e":{
      "scriptId":"u18"},
    "362c9cfbcdfa49afb61a937a89c1ccdb":{
      "scriptId":"u19"},
    "d0efaec3d23c4fdaab7d58c9d6fdf1f8":{
      "scriptId":"u20"}}});